server:
<<<<<<< HEAD
  port: 8099
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myTest?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
=======
  port: 8991
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
>>>>>>> 84478b0e6ec19aced89c091dc4e0d85924165fcd
