server:
  port: 8099
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myTest?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true